'use strict';

/**
 * @ngdoc function
 * @name webappApp.controller:WaterconsumptionIndexCtrl
 * @description
 * # WaterconsumptionIndexCtrl
 * Controller of the webappApp
 */
angular.module('webappApp')
  .controller('WaterconsumptionIndexCtrl', function ($scope) {
    $scope.weeks = [
    	{
    		week:'周一',
    		consumption:'11'
    	},{
    		week:'周二',
    		consumption:'12'
    	},{
    		week:'周三',
    		consumption:'13'
    	},{
    		week:'周四',
    		consumption:'14'
    	},{
    		week:'周五',
    		consumption:'15'
    	},{
    		week:'周六',
    		consumption:'16'
    	},{
    		week:'周日',
    		consumption:'17'
    	}
    ];
    $scope.months = [
    	{
    		day:'3月1日',
    		consumption:'11'
    	},{
    		day:'3月2日',
    		consumption:'12'
    	},{
    		day:'3月3日',
    		consumption:'13'
    	},{
    		day:'3月4日',
    		consumption:'14'
    	},{
    		day:'3月5日',
    		consumption:'15'
    	},{
    		day:'3月6日',
    		consumption:'16'
    	},{
    		day:'3月7日',
    		consumption:'17'
    	},{
    		day:'3月8日',
    		consumption:'18'
    	},{
    		day:'3月9日',
    		consumption:'19'
    	},{
    		day:'3月10日',
    		consumption:'20'
    	},{
    		day:'3月11日',
    		consumption:'11'
    	},{
    		day:'3月12日',
    		consumption:'12'
    	},{
    		day:'3月13日',
    		consumption:'13'
    	},{
    		day:'3月14日',
    		consumption:'14'
    	},{
    		day:'3月15日',
    		consumption:'15'
    	},{
    		day:'3月16日',
    		consumption:'16'
    	},{
    		day:'3月17日',
    		consumption:'17'
    	},{
    		day:'3月18日',
    		consumption:'18'
    	},{
    		day:'3月19日',
    		consumption:'19'
    	},{
    		day:'3月20日',
    		consumption:'20'
    	},{
    		day:'3月21日',
    		consumption:'11'
    	},{
    		day:'3月22日',
    		consumption:'12'
    	},{
    		day:'3月23日',
    		consumption:'13'
    	},{
    		day:'3月24日',
    		consumption:'14'
    	},{
    		day:'3月25日',
    		consumption:'15'
    	},{
    		day:'3月26日',
    		consumption:'16'
    	},{
    		day:'3月27日',
    		consumption:'17'
    	},{
    		day:'3月28日',
    		consumption:'18'
    	},{
    		day:'3月29日',
    		consumption:'19'
    	},{
    		day:'3月30日',
    		consumption:'20'
    	},{
    		day:'3月31日',
    		consumption:'20'
    	}
    ];
  });
